In [24]:
import itertools
import numpy as np

somelists = [
#    [1, 2],
#    [2, 3],
#    [1, 3]
    ['0', '0~'],
    ['1', '1~'],
    ['0', '0~']
]

lists = [
         [1, 2],
         [1, 3],
         [2, 3]
]

print(*itertools.product(*somelists))
print(*itertools.product(*lists))

#for element in itertools.product(*somelists):
#    print(element)

('0', '1', '0') ('0', '1', '0~') ('0', '1~', '0') ('0', '1~', '0~') ('0~', '1', '0') ('0~', '1', '0~') ('0~', '1~', '0') ('0~', '1~', '0~')
(1, 1, 2) (1, 1, 3) (1, 3, 2) (1, 3, 3) (2, 1, 2) (2, 1, 3) (2, 3, 2) (2, 3, 3)


In [25]:
from sympy.logic.boolalg import to_cnf
from sympy.abc import A, B, C, D, E, F, G, H, J


# to_cnf((A & B) | (C & D) | (E & F) | (G & H))
to_cnf((A & B) | (C & D) | (E & F))
# to_cnf((~A & ~B) | (~C & ~D) | (~E & ~F))
# to_cnf((A & B & C) | (D & E & F))

(A | C | E) & (A | C | F) & (A | D | E) & (A | D | F) & (B | C | E) & (B | C | F) & (B | D | E) & (B | D | F)

In [26]:
to_cnf(((~A & B) | (A & ~B)) | ((~C & D) | (C & ~D))) #  | ((~E & F) | (E & ~F)))

(A | B | C | D) & (A | B | C | ~C) & (A | B | D | ~D) & (A | C | D | ~A) & (B | C | D | ~B) & (A | B | ~C | ~D) & (A | C | ~A | ~C) & (A | D | ~A | ~D) & (B | C | ~B | ~C) & (B | D | ~B | ~D) & (C | D | ~A | ~B) & (A | ~A | ~C | ~D) & (B | ~B | ~C | ~D) & (C | ~A | ~B | ~C) & (D | ~A | ~B | ~D) & (~A | ~B | ~C | ~D)

In [27]:
# to_cnf(((A & ~B) | (~A & B)) | ((C & ~D) | (~C & D)) | ((E & ~F) | (~E & F)))
to_cnf(((A & ~B) | (~A & B)) | ((C & ~D) | (~C & D)))

(A | B | C | D) & (A | B | C | ~C) & (A | B | D | ~D) & (A | C | D | ~A) & (B | C | D | ~B) & (A | B | ~C | ~D) & (A | C | ~A | ~C) & (A | D | ~A | ~D) & (B | C | ~B | ~C) & (B | D | ~B | ~D) & (C | D | ~A | ~B) & (A | ~A | ~C | ~D) & (B | ~B | ~C | ~D) & (C | ~A | ~B | ~C) & (D | ~A | ~B | ~D) & (~A | ~B | ~C | ~D)

In [28]:
to_cnf(((A | ~B) & (~A | B)) & ((C | ~D) & (~C | D)))

(A | ~B) & (B | ~A) & (C | ~D) & (D | ~C)

In [29]:
# iter = itertools.product(*[[0, 1], [0, 1], [0, 1], [0, 1]])

# iter = itertools.product(*[[1, 2], [3, 4]])

iter = itertools.product(*[['w1', '~w1'], ['x1', '~x1'], ['w2', '~w2'], ['x2', '~x2']])

for i in iter:
    print(i)

('w1', 'x1', 'w2', 'x2')
('w1', 'x1', 'w2', '~x2')
('w1', 'x1', '~w2', 'x2')
('w1', 'x1', '~w2', '~x2')
('w1', '~x1', 'w2', 'x2')
('w1', '~x1', 'w2', '~x2')
('w1', '~x1', '~w2', 'x2')
('w1', '~x1', '~w2', '~x2')
('~w1', 'x1', 'w2', 'x2')
('~w1', 'x1', 'w2', '~x2')
('~w1', 'x1', '~w2', 'x2')
('~w1', 'x1', '~w2', '~x2')
('~w1', '~x1', 'w2', 'x2')
('~w1', '~x1', 'w2', '~x2')
('~w1', '~x1', '~w2', 'x2')
('~w1', '~x1', '~w2', '~x2')


# Packages

In [30]:
%%capture
!pip install python-sat

In [31]:
from pysat.examples.fm import FM
from pysat.formula import WCNF
from itertools import combinations
import math

import numpy as np

# Prepare indices

In [32]:
n_neurons = 3
n_features = n_neurons
n_train = 4

In [87]:
# define propositional variables for weights
w = np.array([i + 1 for i in range(n_neurons)])
print(f'Propositional weights: {w}')

Propositional weights: [1 2 3]


In [88]:
# define propositional variables for X
# propositional features cannot have same indices as w --> + 1 + max(w)
propositional_features = np.array(
    [[i*n_features + j + max(w) + 1 for j in range(n_features)] for i in range(n_train)]
)
print(propositional_features)

for i in range(propositional_features.shape[0]):
    for j in range(propositional_features.shape[1]):
        print(f'X[{i}][{j}] will be encoded as {propositional_features[i][j]}')

[[ 4  5  6]
 [ 7  8  9]
 [10 11 12]
 [13 14 15]]
X[0][0] will be encoded as 4
X[0][1] will be encoded as 5
X[0][2] will be encoded as 6
X[1][0] will be encoded as 7
X[1][1] will be encoded as 8
X[1][2] will be encoded as 9
X[2][0] will be encoded as 10
X[2][1] will be encoded as 11
X[2][2] will be encoded as 12
X[3][0] will be encoded as 13
X[3][1] will be encoded as 14
X[3][2] will be encoded as 15


In [89]:
# Now we prepare all indices for the case when y == 1

majority_size = int(np.ceil(n_features / 2))
assert(majority_size == np.floor(n_features / 2) + 1)

features_combinations = list(combinations(w, majority_size))
print(features_combinations)  # [(w1 == x_i1) and (w2 == x_i2)] V [(..1) and (..3)] V [(..2) and (..3)]

[(1, 2), (1, 3), (2, 3)]


In [90]:
# Now prepare all products
cartesian_prod = list(itertools.product(*features_combinations))
print(cartesian_prod[:10])

[(1, 1, 2), (1, 1, 3), (1, 3, 2), (1, 3, 3), (2, 1, 2), (2, 1, 3), (2, 3, 2), (2, 3, 3)]


In [91]:
optimized_products = [np.unique(combo).tolist() for combo in cartesian_prod]

def remove_redundant(elements):
    res = []
    for e in elements:
        if not (e in res):
            res.append(e)
    return res

print(optimized_products)
optimized_products = remove_redundant(optimized_products)
print(optimized_products)

[[1, 2], [1, 3], [1, 2, 3], [1, 3], [1, 2], [1, 2, 3], [2, 3], [2, 3]]
[[1, 2], [1, 3], [1, 2, 3], [2, 3]]


# Encode clauses (indices) for case y == 1

In [92]:
# Each element of optimized_products represents:
# [1, 2] --> (w1 == x_i1) V (w2 == x_i2). But we have not transfered to CNF yet
# To do that: [(~w1 V x_i1) & (w1 V ~x_i1)] V [(~w2 V x_i2) & (w2 V ~x_i2)]
# which is 'encoded' as [[1, -1], [2, -2]]

predfinal_clauses = []
for product in optimized_products:
    bracket = []
    for val in product:
        bracket.append([val, -val])
    predfinal_clauses.append(bracket)
predfinal_clauses

[[[1, -1], [2, -2]],
 [[1, -1], [3, -3]],
 [[1, -1], [2, -2], [3, -3]],
 [[2, -2], [3, -3]]]

In [93]:
# And now we are creating final clauses
positive_clauses = []
for predfinal_clause in predfinal_clauses:
    print(f'predfinal_clause = {predfinal_clause}')
    clauses = list(itertools.product(*predfinal_clause))
    print(f'Clauses from it: {clauses}')

    for clause in clauses:
        positive_clauses.append(clause)

# (1, 2) means clause (~w1 V x_i1) V (~w2 V x_i2)
# (-1, 2) means clause (w1 V ~x_i1) V (~w2 V x_i2)
positive_clauses

predfinal_clause = [[1, -1], [2, -2]]
Clauses from it: [(1, 2), (1, -2), (-1, 2), (-1, -2)]
predfinal_clause = [[1, -1], [3, -3]]
Clauses from it: [(1, 3), (1, -3), (-1, 3), (-1, -3)]
predfinal_clause = [[1, -1], [2, -2], [3, -3]]
Clauses from it: [(1, 2, 3), (1, 2, -3), (1, -2, 3), (1, -2, -3), (-1, 2, 3), (-1, 2, -3), (-1, -2, 3), (-1, -2, -3)]
predfinal_clause = [[2, -2], [3, -3]]
Clauses from it: [(2, 3), (2, -3), (-2, 3), (-2, -3)]


[(1, 2),
 (1, -2),
 (-1, 2),
 (-1, -2),
 (1, 3),
 (1, -3),
 (-1, 3),
 (-1, -3),
 (1, 2, 3),
 (1, 2, -3),
 (1, -2, 3),
 (1, -2, -3),
 (-1, 2, 3),
 (-1, 2, -3),
 (-1, -2, 3),
 (-1, -2, -3),
 (2, 3),
 (2, -3),
 (-2, 3),
 (-2, -3)]

# Encode clauses for y == -1

In [94]:
features_combinations

[(1, 2), (1, 3), (2, 3)]

In [137]:
ws_xs_list = []
for combo in features_combinations:
    # print(combo)
    symbols = []
    for i in combo:
        symbols.extend([[f'w {i}', f'~ w {i}']])
        symbols.extend([[f'x {i}', f'~ x {i}']])
    ws_xs_list.append(symbols)

ws_xs_list

[[['w 1', '~ w 1'], ['x 1', '~ x 1'], ['w 2', '~ w 2'], ['x 2', '~ x 2']],
 [['w 1', '~ w 1'], ['x 1', '~ x 1'], ['w 3', '~ w 3'], ['x 3', '~ x 3']],
 [['w 2', '~ w 2'], ['x 2', '~ x 2'], ['w 3', '~ w 3'], ['x 3', '~ x 3']]]

In [138]:
print(*itertools.product(*ws_xs_list[0]))

('w 1', 'x 1', 'w 2', 'x 2') ('w 1', 'x 1', 'w 2', '~ x 2') ('w 1', 'x 1', '~ w 2', 'x 2') ('w 1', 'x 1', '~ w 2', '~ x 2') ('w 1', '~ x 1', 'w 2', 'x 2') ('w 1', '~ x 1', 'w 2', '~ x 2') ('w 1', '~ x 1', '~ w 2', 'x 2') ('w 1', '~ x 1', '~ w 2', '~ x 2') ('~ w 1', 'x 1', 'w 2', 'x 2') ('~ w 1', 'x 1', 'w 2', '~ x 2') ('~ w 1', 'x 1', '~ w 2', 'x 2') ('~ w 1', 'x 1', '~ w 2', '~ x 2') ('~ w 1', '~ x 1', 'w 2', 'x 2') ('~ w 1', '~ x 1', 'w 2', '~ x 2') ('~ w 1', '~ x 1', '~ w 2', 'x 2') ('~ w 1', '~ x 1', '~ w 2', '~ x 2')


In [139]:
negative_clauses = []

for combination in ws_xs_list:
    for clause in itertools.product(*combination):
        # print(clause)
        negative_clauses.append(clause)

In [140]:
# Here, w1 means 1st weight, x1 - first feature of the object
len(set(negative_clauses)), len(negative_clauses)

(48, 48)

# Preparing dataset

In [141]:
sample = [True, False]

np.random.choice(sample, size = (10, 3))

array([[False,  True,  True],
       [ True,  True,  True],
       [False, False,  True],
       [False, False, False],
       [False, False, False],
       [ True, False, False],
       [ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True],
       [ True, False, False]])

In [142]:
def check_if_2nd_feature_true(x):
    return x[1] == True

def test(x):
    pass

def prepare_dataset(n_train_, n_features_, func_):
    sample_arr = [True, False]

    X = np.random.choice(sample_arr, size = (n_train_, n_features_))
    Y = [func_(x) for x in X]
    return X, Y

# Randomly prepare dataset
data_function = check_if_2nd_feature_true

X, Y = prepare_dataset(
    n_train_ = n_train,
    n_features_ = n_features,
    func_ = data_function
)

In [143]:
print(X)
print(Y)

[[ True  True False]
 [False  True  True]
 [ True False False]
 [ True False  True]]
[True, True, False, False]


In [144]:
for x, y in zip(X, Y):
    print(x, data_function(x), y)
    assert(data_function(x) == y)

[ True  True False] True True
[False  True  True] True True
[ True False False] False False
[ True False  True] False False


# Encoding into clauses

In [145]:
positive_clauses

[(1, 2),
 (1, -2),
 (-1, 2),
 (-1, -2),
 (1, 3),
 (1, -3),
 (-1, 3),
 (-1, -3),
 (1, 2, 3),
 (1, 2, -3),
 (1, -2, 3),
 (1, -2, -3),
 (-1, 2, 3),
 (-1, 2, -3),
 (-1, -2, 3),
 (-1, -2, -3),
 (2, 3),
 (2, -3),
 (-2, 3),
 (-2, -3)]

In [156]:


    
    

for negative_clause in negative_clauses[:2]:
    # ('w 1', 'x 1', '~ w 2', '~ x 2')
    clause_to_add = []
    for symbol in negative_clause:
        # symbol is a string, like "w 1" or "~ x 2"
        letters = symbol.split(' ')
        
        if letters[0] == '~':
            x_or_w = letters[1]
        else:
            x_or_w = letters[0]

        clause_to_add.append(calc_update(letters, propositional_features[2], w))
    print(f'neg clause: {negative_clause}')
    print(clause_to_add)

neg clause: ('w 1', 'x 1', 'w 2', 'x 2')
[1, 10, 2, 11]
neg clause: ('w 1', 'x 1', 'w 2', '~ x 2')
[1, 10, 2, -11]


In [154]:
propositional_features[0]

array([4, 5, 6])

In [159]:
positive_clauses

[(1, 2),
 (1, -2),
 (-1, 2),
 (-1, -2),
 (1, 3),
 (1, -3),
 (-1, 3),
 (-1, -3),
 (1, 2, 3),
 (1, 2, -3),
 (1, -2, 3),
 (1, -2, -3),
 (-1, 2, 3),
 (-1, 2, -3),
 (-1, -2, 3),
 (-1, -2, -3),
 (2, 3),
 (2, -3),
 (-2, 3),
 (-2, -3)]

In [160]:
def calc_update(letters, x, w):
    # ['~', 'x', '2']
    x_or_w = ''
    to_put_minus = 1

    if letters[0] == '~':
        x_or_w = letters[1]
        to_put_minus = -1
    else:
        x_or_w = letters[0]
        to_put_minus = 1
    
    index = int(letters[-1])
    if x_or_w == 'x':
        return to_put_minus * x[index - 1]
        
    if x_or_w == 'w':
        return to_put_minus * w[index - 1]

# w[i] is a (i+1)th weight (i.e. w = (1, 2, 3), 1 = w[0], 2 = w[1], 3 = w[2])
wcnf_form = WCNF()

for i in range(len(Y)):
    # x_i = X[i]
    y_i = Y[i]

    if y == True:
        
        for positive_clause in positive_clauses:
            # if (1, -2) clause --> [(w[0] V ~x[i][0]) V (~w[1] V x[i][1])] clause
            clause_to_add = []
            for index in positive_clause:
                abs_index = abs(index)
                prop_weight = w[abs_index - 1]  # variable, where weight is encoded
                prop_feature = propositional_features[i][abs_index - 1]  # feature, that is encoded

                if index < 0:
                    clause_to_add.extend([-prop_weight, prop_feature])
                else:
                    clause_to_add.extend([prop_weight, -prop_feature])
            print(clause_to_add)
            wcnf_form.append(clause_to_add, weight = 1)

    elif y == False:
        
        for negative_clause in negative_clauses[:2]:
            
            # ('w 1', 'x 1', '~ w 2', '~ x 2')
            clause_to_add = []
            for symbol in negative_clause:
                # symbol is a string, like "w 1" or "~ x 2"
                letters = symbol.split(' ')
                clause_to_add.append(calc_update(letters, propositional_features[i], w))
            wcnf_form.append(clause_to_add, weight = 1)

In [158]:
wcnf_form.soft

[[1, 4, 2, 5],
 [1, 4, 2, -5],
 [1, 7, 2, 8],
 [1, 7, 2, -8],
 [1, 10, 2, 11],
 [1, 10, 2, -11],
 [1, 13, 2, 14],
 [1, 13, 2, -14]]

In [79]:
w = WCNF()

w.append([0])

w.hard

[[0]]

# Task

In [ ]:
from pysat.formula import CNF
from pysat.formula import WCNF

In [ ]:
n_neurons = 3
n_train = 3
n_features = n_neurons

assert(n_neurons % 2 == 1)  # odd number of neurons is allowed



In [ ]:
print(X)
print(Y)

[[True, False, False], [False, True, False], [True, True, False]]
[False, True, True]


In [ ]:
# wcnf = WCNF()

# wcnf.append([-1, 2]) 
# wcnf.append([-2, 3])
# wcnf.append([-3, True])
# wcnf.append([4, True])

# print(wcnf.soft)
# print(wcnf.hard)
# print(wcnf.wght)

# fm = FM(wcnf,verbose=10)
# fm.compute()

In [ ]:
# def encode_features(X):
#     n = len(X)
#     m = len(X[0])
#     print(f'Shape of X: n = {n}, m = {m}')
#     prop_features = [[i * n + j + 1 for j in range(m)] for i in range(n)]
#     return np.array(prop_features)


# Encoding weights
prop_weights_indices = [i for i in range(n_neurons)]

In [ ]:
prop_weights_indices

[0, 1, 2]

In [ ]:
group_size = int(math.ceil(n_neurons / 2))
assert group_size == math.floor(n_neurons / 2 + 1)

In [ ]:
combos = list(combinations(prop_weights_indices, group_size))
print(combos[:3])

[(0, 1), (0, 2), (1, 2)]


In [ ]:
cartesian_prod = list(itertools.product(*combos))
print(cartesian_prod)

[(0, 0, 1), (0, 0, 2), (0, 2, 1), (0, 2, 2), (1, 0, 1), (1, 0, 2), (1, 2, 1), (1, 2, 2)]


In [ ]:
clauses_cartesian_products = []
for c in cartesian_prod:
    print(f'Combo: {c}')
    l = [[f'{symb}', f'~{symb}'] for symb in c]
    l_cart_prod = list(itertools.product(*l))
    clauses_cartesian_products += l_cart_prod
    print(l)
    print(l_cart_prod)

Combo: (0, 0, 1)
[['0', '~0'], ['0', '~0'], ['1', '~1']]
[('0', '0', '1'), ('0', '0', '~1'), ('0', '~0', '1'), ('0', '~0', '~1'), ('~0', '0', '1'), ('~0', '0', '~1'), ('~0', '~0', '1'), ('~0', '~0', '~1')]
Combo: (0, 0, 2)
[['0', '~0'], ['0', '~0'], ['2', '~2']]
[('0', '0', '2'), ('0', '0', '~2'), ('0', '~0', '2'), ('0', '~0', '~2'), ('~0', '0', '2'), ('~0', '0', '~2'), ('~0', '~0', '2'), ('~0', '~0', '~2')]
Combo: (0, 2, 1)
[['0', '~0'], ['2', '~2'], ['1', '~1']]
[('0', '2', '1'), ('0', '2', '~1'), ('0', '~2', '1'), ('0', '~2', '~1'), ('~0', '2', '1'), ('~0', '2', '~1'), ('~0', '~2', '1'), ('~0', '~2', '~1')]
Combo: (0, 2, 2)
[['0', '~0'], ['2', '~2'], ['2', '~2']]
[('0', '2', '2'), ('0', '2', '~2'), ('0', '~2', '2'), ('0', '~2', '~2'), ('~0', '2', '2'), ('~0', '2', '~2'), ('~0', '~2', '2'), ('~0', '~2', '~2')]
Combo: (1, 0, 1)
[['1', '~1'], ['0', '~0'], ['1', '~1']]
[('1', '0', '1'), ('1', '0', '~1'), ('1', '~0', '1'), ('1', '~0', '~1'), ('~1', '0', '1'), ('~1', '0', '~1'), ('~1', '~

In [ ]:
clauses_cartesian_products

[('0', '0', '1'),
 ('0', '0', '~1'),
 ('0', '~0', '1'),
 ('0', '~0', '~1'),
 ('~0', '0', '1'),
 ('~0', '0', '~1'),
 ('~0', '~0', '1'),
 ('~0', '~0', '~1'),
 ('0', '0', '2'),
 ('0', '0', '~2'),
 ('0', '~0', '2'),
 ('0', '~0', '~2'),
 ('~0', '0', '2'),
 ('~0', '0', '~2'),
 ('~0', '~0', '2'),
 ('~0', '~0', '~2'),
 ('0', '2', '1'),
 ('0', '2', '~1'),
 ('0', '~2', '1'),
 ('0', '~2', '~1'),
 ('~0', '2', '1'),
 ('~0', '2', '~1'),
 ('~0', '~2', '1'),
 ('~0', '~2', '~1'),
 ('0', '2', '2'),
 ('0', '2', '~2'),
 ('0', '~2', '2'),
 ('0', '~2', '~2'),
 ('~0', '2', '2'),
 ('~0', '2', '~2'),
 ('~0', '~2', '2'),
 ('~0', '~2', '~2'),
 ('1', '0', '1'),
 ('1', '0', '~1'),
 ('1', '~0', '1'),
 ('1', '~0', '~1'),
 ('~1', '0', '1'),
 ('~1', '0', '~1'),
 ('~1', '~0', '1'),
 ('~1', '~0', '~1'),
 ('1', '0', '2'),
 ('1', '0', '~2'),
 ('1', '~0', '2'),
 ('1', '~0', '~2'),
 ('~1', '0', '2'),
 ('~1', '0', '~2'),
 ('~1', '~0', '2'),
 ('~1', '~0', '~2'),
 ('1', '2', '1'),
 ('1', '2', '~1'),
 ('1', '~2', '1'),
 ('1', '

In [ ]:
import numpy as np

print(len(clauses_cartesian_products))
len(np.unique(clauses_cartesian_products))
len(set(clauses_cartesian_products))

64


64

In [ ]:
def encode_prop_features(X):
    n = len(X)
    m = len(X[0])
    prop_features = []
    for i in range(n):
        vals = [i * n + j + len(prop_weights_indices) for j in range(m)]
        prop_features.append(vals)
    

    for i in range(n):
        for j in range(m):
            print(f'X[{i}][{j}] is encoded as {prop_features[i][j]}')

    return prop_features

prop_features = encode_prop_features(X)
print(prop_features)

X[0][0] is encoded as 3
X[0][1] is encoded as 4
X[0][2] is encoded as 5
X[1][0] is encoded as 6
X[1][1] is encoded as 7
X[1][2] is encoded as 8
X[2][0] is encoded as 9
X[2][1] is encoded as 10
X[2][2] is encoded as 11
[[3, 4, 5], [6, 7, 8], [9, 10, 11]]


In [ ]:
unique = [1, 2]
print(get_combinations(unique))

[('w 1', 'x 1', 'w 2', 'x 2'), ('w 1', 'x 1', 'w 2', '~x 2'), ('w 1', 'x 1', '~w 2', 'x 2'), ('w 1', 'x 1', '~w 2', '~x 2'), ('w 1', '~x 1', 'w 2', 'x 2'), ('w 1', '~x 1', 'w 2', '~x 2'), ('w 1', '~x 1', '~w 2', 'x 2'), ('w 1', '~x 1', '~w 2', '~x 2'), ('~w 1', 'x 1', 'w 2', 'x 2'), ('~w 1', 'x 1', 'w 2', '~x 2'), ('~w 1', 'x 1', '~w 2', 'x 2'), ('~w 1', 'x 1', '~w 2', '~x 2'), ('~w 1', '~x 1', 'w 2', 'x 2'), ('~w 1', '~x 1', 'w 2', '~x 2'), ('~w 1', '~x 1', '~w 2', 'x 2'), ('~w 1', '~x 1', '~w 2', '~x 2')]


In [ ]:
clauses_cartesian_products

[('0', '0', '1'),
 ('0', '0', '~1'),
 ('0', '~0', '1'),
 ('0', '~0', '~1'),
 ('~0', '0', '1'),
 ('~0', '0', '~1'),
 ('~0', '~0', '1'),
 ('~0', '~0', '~1'),
 ('0', '0', '2'),
 ('0', '0', '~2'),
 ('0', '~0', '2'),
 ('0', '~0', '~2'),
 ('~0', '0', '2'),
 ('~0', '0', '~2'),
 ('~0', '~0', '2'),
 ('~0', '~0', '~2'),
 ('0', '2', '1'),
 ('0', '2', '~1'),
 ('0', '~2', '1'),
 ('0', '~2', '~1'),
 ('~0', '2', '1'),
 ('~0', '2', '~1'),
 ('~0', '~2', '1'),
 ('~0', '~2', '~1'),
 ('0', '2', '2'),
 ('0', '2', '~2'),
 ('0', '~2', '2'),
 ('0', '~2', '~2'),
 ('~0', '2', '2'),
 ('~0', '2', '~2'),
 ('~0', '~2', '2'),
 ('~0', '~2', '~2'),
 ('1', '0', '1'),
 ('1', '0', '~1'),
 ('1', '~0', '1'),
 ('1', '~0', '~1'),
 ('~1', '0', '1'),
 ('~1', '0', '~1'),
 ('~1', '~0', '1'),
 ('~1', '~0', '~1'),
 ('1', '0', '2'),
 ('1', '0', '~2'),
 ('1', '~0', '2'),
 ('1', '~0', '~2'),
 ('~1', '0', '2'),
 ('~1', '0', '~2'),
 ('~1', '~0', '2'),
 ('~1', '~0', '~2'),
 ('1', '2', '1'),
 ('1', '2', '~1'),
 ('1', '~2', '1'),
 ('1', '

In [ ]:
def get_combinations(unique_combo):
    ws_and_xs = []
    for numb in unique_combo:
        ws_and_xs.append(f'w {numb}')
        ws_and_xs.append(f'x {numb}')
    
    ws_and_xs = [[f'{symb}', f'~{symb}'] for symb in ws_and_xs]
    return list(itertools.product(*ws_and_xs))

def construct_clause_positive(unique_clause_symbols, ):
    clause = []
    # '1' signifies ~w1 V x_i1
    # '~1' signifies w1 V ~x_i1
    for symbol in unique_clause_symbols:  # ('0', '~2', '1')
        if not '~' in symbol:
            # then (e.f. for '1') its not(w_1) V (x_i1)
            index = int(symbol)
            clause.append(-prop_weights_indices[index])
            clause.append(prop_features[i][index])
        elif '~' in symbol:
            # then (e.f. for '1') its (w_1) V not(x_i1)
            symbol = symbol.replace('~', '')
            index = int(symbol)
            clause.append(prop_weights_indices[index])
            clause.append(-prop_features[i][index])
    optimized_clause = list(set(clause))
    return optimized_clause
    
def construct_clause_negative(unique_combo):
    all_combinations = get_combinations(unique_combo)

    clauses = []
    for combination in all_combinations:
        clause = []
        for symbol in combination:
            x_or_w, number = symbol.split(' ')[0], int(symbol.split(' ')[1])
            if x_or_w == 'w':
                clause.append(prop_weights_indices[number])
            if x_or_w == '~w':
                clause.append(-prop_weights_indices[number])
            if x_or_w == 'x':
                clause.append(prop_features[i][number])
            if x_or_w == '~x':
                clause.append(-prop_features[i][number])
        clauses.append(clause)
    return clauses


wcnf = WCNF()
for i in range(len(X)):
    if Y[i] is True:
        for c in clauses_cartesian_products:
            # ('0', '0', '~1')
            # Here we optimize - we dont need to add identical clauses
            unique_clause_symbols = set(c)  # ('0', '0', '1') --> ('0', '1')
            
            # print(set(c), c)
            clause = construct_clause_positive(unique_clause_symbols)
            wcnf.append(clause, weight = 1)
            # print(f'Our clause: {clause}')
    
    elif Y[i] is False:
        # print(f'Y is false')
        for c in cartesian_prod: # (1, 2) (2, 3) (1, 3) --> (1, 2, 1), (1, 2, 3), (1, 3, 1), ...
            # print(f'combo: {c}')
            unique_combo = set(c)  # (1, 2) --> [(~w1 & x_i1) V (w1 & ~x_i1)] V [(~w2 & x_i2) V (w2 & ~x_i2)]
            # print(f'unique combo: {set(unique_combo)}')

            clauses = construct_clause_negative(unique_combo)
            for c in clauses:
                wcnf.append(c, weight = 1)
    # print(clause)
    

In [ ]:
get_combinations([0, 1])

[('w 0', 'x 0', 'w 1', 'x 1'),
 ('w 0', 'x 0', 'w 1', '~x 1'),
 ('w 0', 'x 0', '~w 1', 'x 1'),
 ('w 0', 'x 0', '~w 1', '~x 1'),
 ('w 0', '~x 0', 'w 1', 'x 1'),
 ('w 0', '~x 0', 'w 1', '~x 1'),
 ('w 0', '~x 0', '~w 1', 'x 1'),
 ('w 0', '~x 0', '~w 1', '~x 1'),
 ('~w 0', 'x 0', 'w 1', 'x 1'),
 ('~w 0', 'x 0', 'w 1', '~x 1'),
 ('~w 0', 'x 0', '~w 1', 'x 1'),
 ('~w 0', 'x 0', '~w 1', '~x 1'),
 ('~w 0', '~x 0', 'w 1', 'x 1'),
 ('~w 0', '~x 0', 'w 1', '~x 1'),
 ('~w 0', '~x 0', '~w 1', 'x 1'),
 ('~w 0', '~x 0', '~w 1', '~x 1')]

In [ ]:
construct_clause_negative([0, 1])

[[0, 3, 1, 4],
 [0, 3, 1, -4],
 [0, 3, -1, 4],
 [0, 3, -1, -4],
 [0, -3, 1, 4],
 [0, -3, 1, -4],
 [0, -3, -1, 4],
 [0, -3, -1, -4],
 [0, 3, 1, 4],
 [0, 3, 1, -4],
 [0, 3, -1, 4],
 [0, 3, -1, -4],
 [0, -3, 1, 4],
 [0, -3, 1, -4],
 [0, -3, -1, 4],
 [0, -3, -1, -4]]

In [ ]:
cartesian_prod

[(0, 0, 1),
 (0, 0, 2),
 (0, 2, 1),
 (0, 2, 2),
 (1, 0, 1),
 (1, 0, 2),
 (1, 2, 1),
 (1, 2, 2)]

In [ ]:
len(wcnf.soft)

352

In [ ]:
# Weighted CNF form
wcnf = WCNF()


for x, y in zip(X, Y):
    print(f'Encoding x = {x}, y = {y}')
    
    # At that step, we have combinations of weight indices
    # For example, for 3 weights
    # [(w0 == x_i0) & (w1 == x_i1)] V [(w0 == x_i0) & (w2 == x_i2)] V [(w1 == x_i1) & (w2 == x_i2)]

    # Each combination in cartesian_prod(w_combinations) - is a special clause:
    # For example, for n_weights == 3, after cartesian product, all combinations:
    # (001) (002) (021) (022) (101) (102) (121) (122)
    # Which means (for the first clause (001)):
    # (w_0 == x_i0) | (w_0 == x_i0) | (w_1 == x_i1)

    # However, we still did not expand the equivalence (==):
    # [(~w_0 V x_i0) & (w_0 V ~x_i0)] V [(~w_0 V x_i0) & (w_0 V ~x_i0)] V [(~w_1 V x_i1) & (w_1 V ~x_i1)]

    # And this also has to be transformed into CNF:
    # Do substitution:
    # [(0) & (~0)] V [(0) & (~0)] V [(1) & (~1)]
    # Where 0: ~w_0 V x_i0, ~0: w_0 V ~x_i0
    # We have to transfer (001) -> [[0, ~0], [0, ~0], [1, ~1]] and make a cartesian product of it

    

    

    # for w_combination in combinations(propositional_weights, group_size):
    #     # print(c, c[0], c[1])
    #     # print(propositional_weights.index(c[0]), propositional_weights.index(c[1]))
    #     print(f'weight combination = {w_combination}')
        
    #     for weight in w_combination:
    #         # index of weight --> the same as index of feature of current object x_i in the X dataset
    #         w_index = propositional_weights.index(weight)
    #         x_feature = x[w_index]
    #         print(f'w_{w_index}, x_j = {x_feature}')

    #         # Our clause is - weight == x_feature (equivalence)
    #         # which is (not(weight) V x_feature) and (not(x_feature) V weight)
            
    #         first_clause = [-weight, x_feature]
    #         second_clause = [weight, -x_feature]
    #         wcnf.append



NameError: ignored

In [ ]:
# No hard clauses are introduced.
# Soft clauses - have weight 1, if the prediction of the network is correct
# for a given instance (x_i, y_i) in a dataset

In [ ]:
# Encode this into clauses
for x_i, y_i in zip(X, Y):
    print(f'Encoding x_i = {x_i}, y_i = {y_i}')
    

Encoding x_i = [True, False, False], y_i = False
Encoding x_i = [False, True, False], y_i = True
Encoding x_i = [True, True, False], y_i = True
